[app_servers]
app_node ansible_host=20.203.128.158 ansible_user=Hryshkevich ansible_password=Hryshkevich123! ansible_sudo_pass=Hryshkevich123!
[db_servers]
db_node ansible_host=20.251.114.181 ansible_user=Hryshkevich ansible_password=Hryshkevich123! ansible_sudo_pass=Hryshkevich123!
